
var promptNumber = 1;

var shuffleSequence = seq("instructions", startsWith("training"+promptNumber+"_"), randomize(startsWith("prompt"+promptNumber+"_")),"questionnaire");

var pageTitle = "Prolific Linguistic Survey";
var completionMessage = "The results were successfully sent to the server. You can now validate your participation on Prolific using the following code: CHNJPZ4O. Thanks!";
var completionErrorMessage = "There was an error sending the results to the server. Do not refresh this page. Check your internet connection and try sending the results again.";


var defaults = [
    "Separator", {
        transfer: 1000,
        normalMessage: "Please wait for the next sentence.",
        errorMessage: "Wrong. Please wait for the next sentence.",
        ignoreFailure: true,
        hideProgressBar: true
    },
    "Message", {
       hideProgressBar: true
    },
    "FastScale", {
        startValue: 0,  
        endValue: 100,
        hideProgressBar: false,
        handleLabel: false,
        scaleLabels: ["Definitely not","Definitely"],
        startColor: "#A00000",
        endColor: "#A00000"
    }
];



var items = [

  ["sep", "Separator", {transfer:300, normalMessage:"+"}],

  ["questionnaire", "Form", {html:{include:"questionnaire.html"}}],

  ["instructions", "Message", {html:{include:"instructions_prompt"+promptNumber+".html"}}],
    
// training items

['training1_item1_good', 'FastScale', {html: '<p class=sentence>&ldquo;California borders Oregon, but not Canada.&rdquo;</p><p class=prompt>Does the sentence sound natural?</p>'}],
['training1_item2_bad', 'FastScale', {html: '<p class=sentence>&ldquo;Fifty states US total is.&rdquo;</p><p class=prompt>Does the sentence sound natural?</p>'}],
['training2_item3_good', 'FastScale', {html: '<p class=sentence>&ldquo;California borders Oregon, but not Canada.&rdquo;</p><p class=prompt>Do you think the sentence is true?</p>'}],
['training2_item4_bad', 'FastScale', {html: '<p class=sentence>&ldquo;Texas borders Michigan and Canada.&rdquo;</p><p class=prompt>Do you think the sentence is true?</p>'}],
['training3_item5_good', 'FastScale', {html: '<p class=sentence>&ldquo;Texas borders Michigan and Canada.&rdquo;</p><p class=prompt>Do you think the sentence is false?</p>'}],
['training3_item6_bad', 'FastScale', {html: '<p class=sentence>&ldquo;California borders Oregon, but not Canada.&rdquo;</p><p class=prompt>Do you think the sentence is false?</p>'}],
['training4_item7_good', 'FastScale', {html: '<p class=sentence>&ldquo;California borders Oregon, but not Canada.&rdquo;</p><p class=prompt>Do you understand what the speaker meant?</p>'}],
['training4_item8_bad', 'FastScale', {html: '<p class=sentence>&ldquo;Dogs not at least.&rdquo;</p><p class=prompt>Do you understand what the speaker meant?</p>'}],
['training5_item9_good', 'FastScale', {html: '<p class=sentence>&ldquo;California borders Oregon, but not Canada.&rdquo;</p><p class=prompt>Can you imagine someone genuinely believing this?</p>'}],
['training5_item10_bad', 'FastScale', {html: '<p class=sentence>&ldquo;Bouncy balls are spheres that are cubes.&rdquo;</p><p class=prompt>Can you imagine someone genuinely believing this?</p>'}],
['training6_item11_good', 'FastScale', {html: '<p class=sentence>&ldquo;California borders Oregon, but not Canada.&rdquo;</p><p class=prompt>Could you imagine this sentence being true if the world was different?</p>'}],
['training6_item12_bad', 'FastScale', {html: '<p class=sentence>&ldquo;Bouncy balls are spheres that are cubes.&rdquo;</p><p class=prompt>Could you imagine this sentence being true if the world was different?</p>'}],

// items
['prompt1_item1_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Most people eat breakfast in the morning.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item2_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;The sun rises in the East.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item3_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Dogs can recognize their owners&#39; voices.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item4_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Male cardinals are red.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item5_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Not everyone in the US drives an automatic car.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item6_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;We can list most things discovered by researchers who the scientific community applauded.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item7_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Some people debate which chemical warmed the Earth&#39;s climate after too many factories emitted it.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item8_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Historians know which US historical event started with a protest that alarmed the British authorities.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item9_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Art students learn which famous painting Da Vinci created together with The Last Supper.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item10_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Librarians usually know which author wrote which famous novel.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item11_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;We can list most things which the scientific community applauded the researchers who discovered.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item12_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Scientists have discussed which chemical the Earth underwent climate change after too many factories emitted.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item13_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Historians know which US historical event the protest that started alarmed the British authorities.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item14_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Art students learn which famous painting Da Vinci created The Last Supper and.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item15_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Librarians usually know which author which famous novel wrote.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item16_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;The pigs grunts.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item17_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;After Shakespeare became famous, people knew he to be the author of Hamlet.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item18_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;Empire the Roman collapsed.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item19_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;Astronauts not reached the Mars.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item20_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;Itself rotates the Earth.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item21_processing', 'FastScale', {html: '<p class="sentence">&ldquo;Fat people eat accumulates in their bodies.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item22_processing', 'FastScale', {html: '<p class="sentence">&ldquo;When a doctor examines some patients worry they might be sick.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item23_processing', 'FastScale', {html: '<p class="sentence">&ldquo;When the ice melts the ground in Northern cities becomes wet.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item24_processing', 'FastScale', {html: '<p class="sentence">&ldquo;The language that the country that borders Canada uses is English.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item25_processing', 'FastScale', {html: '<p class="sentence">&ldquo;Scientists who the committee awards the Nobel Prize to are celebrated worldwide.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item26_false', 'FastScale', {html: '<p class="sentence">&ldquo;Bananas grow on pine trees.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item27_false', 'FastScale', {html: '<p class="sentence">&ldquo;The Pacific Ocean is smaller than Lake Michigan.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item28_false', 'FastScale', {html: '<p class="sentence">&ldquo;Male cardinals are blue.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item29_false', 'FastScale', {html: '<p class="sentence">&ldquo;Everyone in the US drives a manual transmission.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item30_false', 'FastScale', {html: '<p class="sentence">&ldquo;The sun rises in the West.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item31_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;The number seven is both odd and even.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item32_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;An empty swimming pool is full.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item33_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;By population, Texas is larger and smaller than California.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item34_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;In 2017, the Eagles won the Super Bowl for the very first time again.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item35_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;North Carolina has a smaller population than Virginia, and vice versa.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item36_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;The most populated US city has more inhabitants than the fifth one.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item37_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;A full swimming pool isn&#39;t empty.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item38_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;Illinois has either more or less population than Maryland.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item39_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;When it rains, it rains.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item40_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;When it rains and the pavement becomes wet, it stops being dry.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item41_magri', 'FastScale', {html: '<p class="sentence">&ldquo;Some Canadians come from a cold country.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item42_magri', 'FastScale', {html: '<p class="sentence">&ldquo;Some elephants are mammals.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item43_magri', 'FastScale', {html: '<p class="sentence">&ldquo;Everyone&#39;s left hand or right hand is different from the other.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item44_magri', 'FastScale', {html: '<p class="sentence">&ldquo;California or Oregon have the same time zone.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item45_magri', 'FastScale', {html: '<p class="sentence">&ldquo;LeBron James is sometimes tall.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item46_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Dogs walk on both their legs.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item47_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;The US state north of Alaska has terrible winters.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item48_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Americans recently stopped driving on the left.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item49_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Both states bordering Texas have smaller populations.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item50_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;The US state that borders China has a warm climate.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item51_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Most people can hold a pound with all their hands.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item52_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;A mother of the defendant usually attends trials.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item53_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Humans have better depth perception when viewing an object with all their eyes.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item54_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;A supreme court of the US can override decisions by lower courts.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item55_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;If it rains, meteorologists believe it.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item56_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There are most motorized cars.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item57_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There is every fluffy animal.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item58_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There are both eyes on the face of mammals.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item59_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There are the 50 states in the United States.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item60_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There is Mount Everest&#39;s summit in the Himalayas.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item61_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;Humans have ever been to the moon.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item62_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;Michael Jackson has won any Grammy Award.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item63_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;A bee has ever pollinated a flower.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item64_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;A modern car has any airbags.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item65_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;The 20th century saw any technological advancements.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item66_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Parents usually hope whether their children pass important exams.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item67_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;In medieval times, people believed whether the sun revolved around the earth.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item68_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Astronauts hope whether their rockets are safe to fly.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item69_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Many adults today believe whether eating fresh fruits and vegetables is healthy.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item70_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Scientists believe whether the universe is expanding.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item71_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which atom the scientists know is the smallest.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item72_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which mountain people know is the highest on earth.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item73_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which US president people know is the first.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item74_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear who people know is the longest river in the US.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt1_item75_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which solar planet astronauts know is the closest to the sun.&rdquo;</p><p class="prompt">Does the sentence sound natural?</p>'}],
['prompt2_item1_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Most people eat breakfast in the morning.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item2_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;The sun rises in the East.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item3_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Dogs can recognize their owners&#39; voices.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item4_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Male cardinals are red.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item5_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Not everyone in the US drives an automatic car.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item6_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;We can list most things discovered by researchers who the scientific community applauded.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item7_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Some people debate which chemical warmed the Earth&#39;s climate after too many factories emitted it.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item8_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Historians know which US historical event started with a protest that alarmed the British authorities.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item9_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Art students learn which famous painting Da Vinci created together with The Last Supper.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item10_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Librarians usually know which author wrote which famous novel.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item11_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;We can list most things which the scientific community applauded the researchers who discovered.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item12_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Scientists have discussed which chemical the Earth underwent climate change after too many factories emitted.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item13_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Historians know which US historical event the protest that started alarmed the British authorities.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item14_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Art students learn which famous painting Da Vinci created The Last Supper and.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item15_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Librarians usually know which author which famous novel wrote.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item16_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;The pigs grunts.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item17_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;After Shakespeare became famous, people knew he to be the author of Hamlet.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item18_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;Empire the Roman collapsed.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item19_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;Astronauts not reached the Mars.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item20_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;Itself rotates the Earth.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item21_processing', 'FastScale', {html: '<p class="sentence">&ldquo;Fat people eat accumulates in their bodies.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item22_processing', 'FastScale', {html: '<p class="sentence">&ldquo;When a doctor examines some patients worry they might be sick.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item23_processing', 'FastScale', {html: '<p class="sentence">&ldquo;When the ice melts the ground in Northern cities becomes wet.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item24_processing', 'FastScale', {html: '<p class="sentence">&ldquo;The language that the country that borders Canada uses is English.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item25_processing', 'FastScale', {html: '<p class="sentence">&ldquo;Scientists who the committee awards the Nobel Prize to are celebrated worldwide.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item26_false', 'FastScale', {html: '<p class="sentence">&ldquo;Bananas grow on pine trees.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item27_false', 'FastScale', {html: '<p class="sentence">&ldquo;The Pacific Ocean is smaller than Lake Michigan.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item28_false', 'FastScale', {html: '<p class="sentence">&ldquo;Male cardinals are blue.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item29_false', 'FastScale', {html: '<p class="sentence">&ldquo;Everyone in the US drives a manual transmission.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item30_false', 'FastScale', {html: '<p class="sentence">&ldquo;The sun rises in the West.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item31_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;The number seven is both odd and even.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item32_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;An empty swimming pool is full.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item33_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;By population, Texas is larger and smaller than California.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item34_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;In 2017, the Eagles won the Super Bowl for the very first time again.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item35_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;North Carolina has a smaller population than Virginia, and vice versa.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item36_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;The most populated US city has more inhabitants than the fifth one.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item37_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;A full swimming pool isn&#39;t empty.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item38_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;Illinois has either more or less population than Maryland.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item39_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;When it rains, it rains.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item40_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;When it rains and the pavement becomes wet, it stops being dry.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item41_magri', 'FastScale', {html: '<p class="sentence">&ldquo;Some Canadians come from a cold country.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item42_magri', 'FastScale', {html: '<p class="sentence">&ldquo;Some elephants are mammals.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item43_magri', 'FastScale', {html: '<p class="sentence">&ldquo;Everyone&#39;s left hand or right hand is different from the other.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item44_magri', 'FastScale', {html: '<p class="sentence">&ldquo;California or Oregon have the same time zone.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item45_magri', 'FastScale', {html: '<p class="sentence">&ldquo;LeBron James is sometimes tall.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item46_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Dogs walk on both their legs.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item47_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;The US state north of Alaska has terrible winters.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item48_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Americans recently stopped driving on the left.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item49_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Both states bordering Texas have smaller populations.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item50_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;The US state that borders China has a warm climate.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item51_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Most people can hold a pound with all their hands.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item52_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;A mother of the defendant usually attends trials.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item53_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Humans have better depth perception when viewing an object with all their eyes.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item54_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;A supreme court of the US can override decisions by lower courts.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item55_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;If it rains, meteorologists believe it.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item56_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There are most motorized cars.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item57_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There is every fluffy animal.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item58_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There are both eyes on the face of mammals.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item59_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There are the 50 states in the United States.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item60_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There is Mount Everest&#39;s summit in the Himalayas.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item61_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;Humans have ever been to the moon.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item62_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;Michael Jackson has won any Grammy Award.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item63_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;A bee has ever pollinated a flower.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item64_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;A modern car has any airbags.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item65_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;The 20th century saw any technological advancements.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item66_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Parents usually hope whether their children pass important exams.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item67_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;In medieval times, people believed whether the sun revolved around the earth.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item68_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Astronauts hope whether their rockets are safe to fly.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item69_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Many adults today believe whether eating fresh fruits and vegetables is healthy.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item70_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Scientists believe whether the universe is expanding.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item71_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which atom the scientists know is the smallest.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item72_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which mountain people know is the highest on earth.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item73_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which US president people know is the first.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item74_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear who people know is the longest river in the US.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt2_item75_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which solar planet astronauts know is the closest to the sun.&rdquo;</p><p class="prompt">Do you think the sentence is true?</p>'}],
['prompt3_item1_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Most people eat breakfast in the morning.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item2_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;The sun rises in the East.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item3_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Dogs can recognize their owners&#39; voices.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item4_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Male cardinals are red.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item5_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Not everyone in the US drives an automatic car.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item6_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;We can list most things discovered by researchers who the scientific community applauded.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item7_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Some people debate which chemical warmed the Earth&#39;s climate after too many factories emitted it.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item8_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Historians know which US historical event started with a protest that alarmed the British authorities.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item9_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Art students learn which famous painting Da Vinci created together with The Last Supper.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item10_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Librarians usually know which author wrote which famous novel.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item11_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;We can list most things which the scientific community applauded the researchers who discovered.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item12_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Scientists have discussed which chemical the Earth underwent climate change after too many factories emitted.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item13_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Historians know which US historical event the protest that started alarmed the British authorities.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item14_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Art students learn which famous painting Da Vinci created The Last Supper and.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item15_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Librarians usually know which author which famous novel wrote.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item16_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;The pigs grunts.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item17_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;After Shakespeare became famous, people knew he to be the author of Hamlet.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item18_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;Empire the Roman collapsed.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item19_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;Astronauts not reached the Mars.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item20_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;Itself rotates the Earth.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item21_processing', 'FastScale', {html: '<p class="sentence">&ldquo;Fat people eat accumulates in their bodies.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item22_processing', 'FastScale', {html: '<p class="sentence">&ldquo;When a doctor examines some patients worry they might be sick.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item23_processing', 'FastScale', {html: '<p class="sentence">&ldquo;When the ice melts the ground in Northern cities becomes wet.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item24_processing', 'FastScale', {html: '<p class="sentence">&ldquo;The language that the country that borders Canada uses is English.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item25_processing', 'FastScale', {html: '<p class="sentence">&ldquo;Scientists who the committee awards the Nobel Prize to are celebrated worldwide.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item26_false', 'FastScale', {html: '<p class="sentence">&ldquo;Bananas grow on pine trees.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item27_false', 'FastScale', {html: '<p class="sentence">&ldquo;The Pacific Ocean is smaller than Lake Michigan.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item28_false', 'FastScale', {html: '<p class="sentence">&ldquo;Male cardinals are blue.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item29_false', 'FastScale', {html: '<p class="sentence">&ldquo;Everyone in the US drives a manual transmission.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item30_false', 'FastScale', {html: '<p class="sentence">&ldquo;The sun rises in the West.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item31_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;The number seven is both odd and even.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item32_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;An empty swimming pool is full.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item33_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;By population, Texas is larger and smaller than California.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item34_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;In 2017, the Eagles won the Super Bowl for the very first time again.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item35_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;North Carolina has a smaller population than Virginia, and vice versa.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item36_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;The most populated US city has more inhabitants than the fifth one.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item37_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;A full swimming pool isn&#39;t empty.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item38_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;Illinois has either more or less population than Maryland.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item39_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;When it rains, it rains.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item40_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;When it rains and the pavement becomes wet, it stops being dry.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item41_magri', 'FastScale', {html: '<p class="sentence">&ldquo;Some Canadians come from a cold country.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item42_magri', 'FastScale', {html: '<p class="sentence">&ldquo;Some elephants are mammals.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item43_magri', 'FastScale', {html: '<p class="sentence">&ldquo;Everyone&#39;s left hand or right hand is different from the other.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item44_magri', 'FastScale', {html: '<p class="sentence">&ldquo;California or Oregon have the same time zone.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item45_magri', 'FastScale', {html: '<p class="sentence">&ldquo;LeBron James is sometimes tall.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item46_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Dogs walk on both their legs.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item47_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;The US state north of Alaska has terrible winters.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item48_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Americans recently stopped driving on the left.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item49_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Both states bordering Texas have smaller populations.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item50_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;The US state that borders China has a warm climate.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item51_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Most people can hold a pound with all their hands.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item52_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;A mother of the defendant usually attends trials.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item53_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Humans have better depth perception when viewing an object with all their eyes.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item54_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;A supreme court of the US can override decisions by lower courts.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item55_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;If it rains, meteorologists believe it.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item56_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There are most motorized cars.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item57_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There is every fluffy animal.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item58_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There are both eyes on the face of mammals.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item59_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There are the 50 states in the United States.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item60_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There is Mount Everest&#39;s summit in the Himalayas.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item61_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;Humans have ever been to the moon.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item62_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;Michael Jackson has won any Grammy Award.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item63_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;A bee has ever pollinated a flower.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item64_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;A modern car has any airbags.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item65_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;The 20th century saw any technological advancements.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item66_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Parents usually hope whether their children pass important exams.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item67_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;In medieval times, people believed whether the sun revolved around the earth.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item68_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Astronauts hope whether their rockets are safe to fly.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item69_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Many adults today believe whether eating fresh fruits and vegetables is healthy.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item70_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Scientists believe whether the universe is expanding.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item71_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which atom the scientists know is the smallest.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item72_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which mountain people know is the highest on earth.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item73_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which US president people know is the first.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item74_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear who people know is the longest river in the US.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt3_item75_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which solar planet astronauts know is the closest to the sun.&rdquo;</p><p class="prompt">Do you think the sentence is false?</p>'}],
['prompt4_item1_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Most people eat breakfast in the morning.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item2_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;The sun rises in the East.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item3_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Dogs can recognize their owners&#39; voices.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item4_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Male cardinals are red.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item5_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Not everyone in the US drives an automatic car.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item6_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;We can list most things discovered by researchers who the scientific community applauded.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item7_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Some people debate which chemical warmed the Earth&#39;s climate after too many factories emitted it.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item8_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Historians know which US historical event started with a protest that alarmed the British authorities.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item9_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Art students learn which famous painting Da Vinci created together with The Last Supper.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item10_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Librarians usually know which author wrote which famous novel.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item11_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;We can list most things which the scientific community applauded the researchers who discovered.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item12_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Scientists have discussed which chemical the Earth underwent climate change after too many factories emitted.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item13_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Historians know which US historical event the protest that started alarmed the British authorities.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item14_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Art students learn which famous painting Da Vinci created The Last Supper and.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item15_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Librarians usually know which author which famous novel wrote.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item16_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;The pigs grunts.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item17_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;After Shakespeare became famous, people knew he to be the author of Hamlet.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item18_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;Empire the Roman collapsed.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item19_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;Astronauts not reached the Mars.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item20_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;Itself rotates the Earth.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item21_processing', 'FastScale', {html: '<p class="sentence">&ldquo;Fat people eat accumulates in their bodies.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item22_processing', 'FastScale', {html: '<p class="sentence">&ldquo;When a doctor examines some patients worry they might be sick.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item23_processing', 'FastScale', {html: '<p class="sentence">&ldquo;When the ice melts the ground in Northern cities becomes wet.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item24_processing', 'FastScale', {html: '<p class="sentence">&ldquo;The language that the country that borders Canada uses is English.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item25_processing', 'FastScale', {html: '<p class="sentence">&ldquo;Scientists who the committee awards the Nobel Prize to are celebrated worldwide.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item26_false', 'FastScale', {html: '<p class="sentence">&ldquo;Bananas grow on pine trees.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item27_false', 'FastScale', {html: '<p class="sentence">&ldquo;The Pacific Ocean is smaller than Lake Michigan.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item28_false', 'FastScale', {html: '<p class="sentence">&ldquo;Male cardinals are blue.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item29_false', 'FastScale', {html: '<p class="sentence">&ldquo;Everyone in the US drives a manual transmission.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item30_false', 'FastScale', {html: '<p class="sentence">&ldquo;The sun rises in the West.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item31_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;The number seven is both odd and even.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item32_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;An empty swimming pool is full.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item33_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;By population, Texas is larger and smaller than California.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item34_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;In 2017, the Eagles won the Super Bowl for the very first time again.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item35_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;North Carolina has a smaller population than Virginia, and vice versa.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item36_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;The most populated US city has more inhabitants than the fifth one.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item37_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;A full swimming pool isn&#39;t empty.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item38_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;Illinois has either more or less population than Maryland.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item39_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;When it rains, it rains.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item40_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;When it rains and the pavement becomes wet, it stops being dry.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item41_magri', 'FastScale', {html: '<p class="sentence">&ldquo;Some Canadians come from a cold country.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item42_magri', 'FastScale', {html: '<p class="sentence">&ldquo;Some elephants are mammals.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item43_magri', 'FastScale', {html: '<p class="sentence">&ldquo;Everyone&#39;s left hand or right hand is different from the other.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item44_magri', 'FastScale', {html: '<p class="sentence">&ldquo;California or Oregon have the same time zone.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item45_magri', 'FastScale', {html: '<p class="sentence">&ldquo;LeBron James is sometimes tall.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item46_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Dogs walk on both their legs.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item47_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;The US state north of Alaska has terrible winters.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item48_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Americans recently stopped driving on the left.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item49_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Both states bordering Texas have smaller populations.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item50_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;The US state that borders China has a warm climate.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item51_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Most people can hold a pound with all their hands.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item52_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;A mother of the defendant usually attends trials.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item53_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Humans have better depth perception when viewing an object with all their eyes.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item54_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;A supreme court of the US can override decisions by lower courts.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item55_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;If it rains, meteorologists believe it.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item56_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There are most motorized cars.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item57_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There is every fluffy animal.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item58_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There are both eyes on the face of mammals.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item59_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There are the 50 states in the United States.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item60_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There is Mount Everest&#39;s summit in the Himalayas.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item61_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;Humans have ever been to the moon.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item62_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;Michael Jackson has won any Grammy Award.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item63_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;A bee has ever pollinated a flower.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item64_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;A modern car has any airbags.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item65_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;The 20th century saw any technological advancements.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item66_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Parents usually hope whether their children pass important exams.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item67_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;In medieval times, people believed whether the sun revolved around the earth.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item68_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Astronauts hope whether their rockets are safe to fly.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item69_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Many adults today believe whether eating fresh fruits and vegetables is healthy.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item70_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Scientists believe whether the universe is expanding.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item71_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which atom the scientists know is the smallest.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item72_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which mountain people know is the highest on earth.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item73_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which US president people know is the first.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item74_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear who people know is the longest river in the US.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt4_item75_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which solar planet astronauts know is the closest to the sun.&rdquo;</p><p class="prompt">Do you understand what the speaker meant?</p>'}],
['prompt5_item1_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Most people eat breakfast in the morning.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item2_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;The sun rises in the East.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item3_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Dogs can recognize their owners&#39; voices.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item4_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Male cardinals are red.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item5_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Not everyone in the US drives an automatic car.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item6_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;We can list most things discovered by researchers who the scientific community applauded.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item7_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Some people debate which chemical warmed the Earth&#39;s climate after too many factories emitted it.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item8_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Historians know which US historical event started with a protest that alarmed the British authorities.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item9_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Art students learn which famous painting Da Vinci created together with The Last Supper.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item10_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Librarians usually know which author wrote which famous novel.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item11_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;We can list most things which the scientific community applauded the researchers who discovered.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item12_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Scientists have discussed which chemical the Earth underwent climate change after too many factories emitted.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item13_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Historians know which US historical event the protest that started alarmed the British authorities.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item14_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Art students learn which famous painting Da Vinci created The Last Supper and.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item15_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Librarians usually know which author which famous novel wrote.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item16_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;The pigs grunts.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item17_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;After Shakespeare became famous, people knew he to be the author of Hamlet.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item18_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;Empire the Roman collapsed.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item19_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;Astronauts not reached the Mars.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item20_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;Itself rotates the Earth.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item21_processing', 'FastScale', {html: '<p class="sentence">&ldquo;Fat people eat accumulates in their bodies.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item22_processing', 'FastScale', {html: '<p class="sentence">&ldquo;When a doctor examines some patients worry they might be sick.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item23_processing', 'FastScale', {html: '<p class="sentence">&ldquo;When the ice melts the ground in Northern cities becomes wet.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item24_processing', 'FastScale', {html: '<p class="sentence">&ldquo;The language that the country that borders Canada uses is English.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item25_processing', 'FastScale', {html: '<p class="sentence">&ldquo;Scientists who the committee awards the Nobel Prize to are celebrated worldwide.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item26_false', 'FastScale', {html: '<p class="sentence">&ldquo;Bananas grow on pine trees.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item27_false', 'FastScale', {html: '<p class="sentence">&ldquo;The Pacific Ocean is smaller than Lake Michigan.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item28_false', 'FastScale', {html: '<p class="sentence">&ldquo;Male cardinals are blue.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item29_false', 'FastScale', {html: '<p class="sentence">&ldquo;Everyone in the US drives a manual transmission.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item30_false', 'FastScale', {html: '<p class="sentence">&ldquo;The sun rises in the West.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item31_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;The number seven is both odd and even.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item32_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;An empty swimming pool is full.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item33_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;By population, Texas is larger and smaller than California.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item34_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;In 2017, the Eagles won the Super Bowl for the very first time again.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item35_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;North Carolina has a smaller population than Virginia, and vice versa.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item36_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;The most populated US city has more inhabitants than the fifth one.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item37_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;A full swimming pool isn&#39;t empty.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item38_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;Illinois has either more or less population than Maryland.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item39_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;When it rains, it rains.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item40_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;When it rains and the pavement becomes wet, it stops being dry.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item41_magri', 'FastScale', {html: '<p class="sentence">&ldquo;Some Canadians come from a cold country.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item42_magri', 'FastScale', {html: '<p class="sentence">&ldquo;Some elephants are mammals.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item43_magri', 'FastScale', {html: '<p class="sentence">&ldquo;Everyone&#39;s left hand or right hand is different from the other.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item44_magri', 'FastScale', {html: '<p class="sentence">&ldquo;California or Oregon have the same time zone.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item45_magri', 'FastScale', {html: '<p class="sentence">&ldquo;LeBron James is sometimes tall.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item46_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Dogs walk on both their legs.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item47_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;The US state north of Alaska has terrible winters.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item48_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Americans recently stopped driving on the left.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item49_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Both states bordering Texas have smaller populations.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item50_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;The US state that borders China has a warm climate.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item51_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Most people can hold a pound with all their hands.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item52_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;A mother of the defendant usually attends trials.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item53_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Humans have better depth perception when viewing an object with all their eyes.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item54_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;A supreme court of the US can override decisions by lower courts.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item55_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;If it rains, meteorologists believe it.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item56_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There are most motorized cars.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item57_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There is every fluffy animal.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item58_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There are both eyes on the face of mammals.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item59_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There are the 50 states in the United States.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item60_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There is Mount Everest&#39;s summit in the Himalayas.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item61_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;Humans have ever been to the moon.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item62_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;Michael Jackson has won any Grammy Award.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item63_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;A bee has ever pollinated a flower.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item64_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;A modern car has any airbags.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item65_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;The 20th century saw any technological advancements.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item66_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Parents usually hope whether their children pass important exams.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item67_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;In medieval times, people believed whether the sun revolved around the earth.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item68_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Astronauts hope whether their rockets are safe to fly.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item69_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Many adults today believe whether eating fresh fruits and vegetables is healthy.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item70_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Scientists believe whether the universe is expanding.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item71_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which atom the scientists know is the smallest.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item72_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which mountain people know is the highest on earth.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item73_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which US president people know is the first.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item74_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear who people know is the longest river in the US.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt5_item75_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which solar planet astronauts know is the closest to the sun.&rdquo;</p><p class="prompt">Can you imagine someone genuinely believing this?</p>'}],
['prompt6_item1_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Most people eat breakfast in the morning.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item2_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;The sun rises in the East.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item3_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Dogs can recognize their owners&#39; voices.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item4_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Male cardinals are red.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item5_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Not everyone in the US drives an automatic car.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item6_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;We can list most things discovered by researchers who the scientific community applauded.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item7_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Some people debate which chemical warmed the Earth&#39;s climate after too many factories emitted it.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item8_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Historians know which US historical event started with a protest that alarmed the British authorities.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item9_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Art students learn which famous painting Da Vinci created together with The Last Supper.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item10_goodControls', 'FastScale', {html: '<p class="sentence">&ldquo;Librarians usually know which author wrote which famous novel.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item11_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;We can list most things which the scientific community applauded the researchers who discovered.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item12_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Scientists have discussed which chemical the Earth underwent climate change after too many factories emitted.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item13_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Historians know which US historical event the protest that started alarmed the British authorities.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item14_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Art students learn which famous painting Da Vinci created The Last Supper and.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item15_syntax1', 'FastScale', {html: '<p class="sentence">&ldquo;Librarians usually know which author which famous novel wrote.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item16_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;The pigs grunts.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item17_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;After Shakespeare became famous, people knew he to be the author of Hamlet.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item18_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;Empire the Roman collapsed.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item19_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;Astronauts not reached the Mars.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item20_syntax2', 'FastScale', {html: '<p class="sentence">&ldquo;Itself rotates the Earth.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item21_processing', 'FastScale', {html: '<p class="sentence">&ldquo;Fat people eat accumulates in their bodies.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item22_processing', 'FastScale', {html: '<p class="sentence">&ldquo;When a doctor examines some patients worry they might be sick.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item23_processing', 'FastScale', {html: '<p class="sentence">&ldquo;When the ice melts the ground in Northern cities becomes wet.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item24_processing', 'FastScale', {html: '<p class="sentence">&ldquo;The language that the country that borders Canada uses is English.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item25_processing', 'FastScale', {html: '<p class="sentence">&ldquo;Scientists who the committee awards the Nobel Prize to are celebrated worldwide.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item26_false', 'FastScale', {html: '<p class="sentence">&ldquo;Bananas grow on pine trees.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item27_false', 'FastScale', {html: '<p class="sentence">&ldquo;The Pacific Ocean is smaller than Lake Michigan.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item28_false', 'FastScale', {html: '<p class="sentence">&ldquo;Male cardinals are blue.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item29_false', 'FastScale', {html: '<p class="sentence">&ldquo;Everyone in the US drives a manual transmission.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item30_false', 'FastScale', {html: '<p class="sentence">&ldquo;The sun rises in the West.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item31_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;The number seven is both odd and even.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item32_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;An empty swimming pool is full.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item33_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;By population, Texas is larger and smaller than California.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item34_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;In 2017, the Eagles won the Super Bowl for the very first time again.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item35_contradiction', 'FastScale', {html: '<p class="sentence">&ldquo;North Carolina has a smaller population than Virginia, and vice versa.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item36_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;The most populated US city has more inhabitants than the fifth one.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item37_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;A full swimming pool isn&#39;t empty.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item38_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;Illinois has either more or less population than Maryland.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item39_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;When it rains, it rains.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item40_tautology', 'FastScale', {html: '<p class="sentence">&ldquo;When it rains and the pavement becomes wet, it stops being dry.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item41_magri', 'FastScale', {html: '<p class="sentence">&ldquo;Some Canadians come from a cold country.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item42_magri', 'FastScale', {html: '<p class="sentence">&ldquo;Some elephants are mammals.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item43_magri', 'FastScale', {html: '<p class="sentence">&ldquo;Everyone&#39;s left hand or right hand is different from the other.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item44_magri', 'FastScale', {html: '<p class="sentence">&ldquo;California or Oregon have the same time zone.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item45_magri', 'FastScale', {html: '<p class="sentence">&ldquo;LeBron James is sometimes tall.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item46_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Dogs walk on both their legs.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item47_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;The US state north of Alaska has terrible winters.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item48_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Americans recently stopped driving on the left.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item49_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Both states bordering Texas have smaller populations.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item50_presupFailure', 'FastScale', {html: '<p class="sentence">&ldquo;The US state that borders China has a warm climate.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item51_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Most people can hold a pound with all their hands.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item52_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;A mother of the defendant usually attends trials.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item53_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;Humans have better depth perception when viewing an object with all their eyes.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item54_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;A supreme court of the US can override decisions by lower courts.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item55_MPFailure', 'FastScale', {html: '<p class="sentence">&ldquo;If it rains, meteorologists believe it.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item56_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There are most motorized cars.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item57_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There is every fluffy animal.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item58_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There are both eyes on the face of mammals.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item59_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There are the 50 states in the United States.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item60_logicality1', 'FastScale', {html: '<p class="sentence">&ldquo;There is Mount Everest&#39;s summit in the Himalayas.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item61_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;Humans have ever been to the moon.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item62_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;Michael Jackson has won any Grammy Award.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item63_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;A bee has ever pollinated a flower.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item64_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;A modern car has any airbags.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item65_logicality2', 'FastScale', {html: '<p class="sentence">&ldquo;The 20th century saw any technological advancements.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item66_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Parents usually hope whether their children pass important exams.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item67_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;In medieval times, people believed whether the sun revolved around the earth.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item68_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Astronauts hope whether their rockets are safe to fly.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item69_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Many adults today believe whether eating fresh fruits and vegetables is healthy.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item70_logicality3', 'FastScale', {html: '<p class="sentence">&ldquo;Scientists believe whether the universe is expanding.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item71_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which atom the scientists know is the smallest.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item72_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which mountain people know is the highest on earth.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item73_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which US president people know is the first.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item74_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear who people know is the longest river in the US.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
['prompt6_item75_logicality4', 'FastScale', {html: '<p class="sentence">&ldquo;It is clear which solar planet astronauts know is the closest to the sun.&rdquo;</p><p class="prompt">Could you imagine this sentence being true if the world was different?</p>'}],
];

